### ISSUE TITLE
Ruleset 1 Unit Tests

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/tee-worker#33]
**Tasks**
- [ ] Create TEE unit test: Check Ruleset 1 succeeds and generates a VC successfully
- [ ] Create TEE unit test: Check Ruleset 1 should fail successfully when no Web2.0 account is linked 
- [ ] Create TEE unit test: Check Ruleset 1 should fail successfully when no Web3 address is linked

**Details**

**Unit Test 1**: **Ruleset 1 succeeds** and generates a VC successfully 
(Ref: Link and verify a Web2.0 and Web3 account)

- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
- The extrinsic should then look-up the `ruleset-id` param and run the associated  functionality which should validate the following are true:
  - The `idhub-address` has both linked and verified at least one Web2.0 account
  - The `idhub-address` has both linked and verified at least one Web3 address/account
- If the condition is **true** the TEE should create a VC in the format of a credential schema (JSON) Ref: [https://www.w3.org/TR/vc-data-model/#example-a-simple-example-of-a-verifiable-credential](https://www.w3.org/TR/vc-data-model/#example-a-simple-example-of-a-verifiable-credential)
    - The TEE should then callback the a Parachain extrinsic (e.g. **VCGenerated**) and pass the VC to it
    - The unit test should be marked as passed if the VC generates and Parachain extrinsic is successfully called

**Unit Test 2**: Test **Ruleset 1** should **fail** successfully **when no Web2.0 account is linked**

- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
- The extrinsic should then look-up the `ruleset-id` param and run the associated  functionality which should validate the following statements are true:
- The `idhub-address` has **NOT** linked at least one Web2.0 account
- The `idhub-address` has both linked and verified at least one Web3 address/account

**Unit Test 3**: Test **Ruleset 1** should **fail** successfully **when no Web3 address is linked**

- **Generate VC** extrinsic within the TEE Enclave should be called
  - The extrinsic should accept the following params:
    - `ruleset-id` param relating to the set of rules we need to test against
    - `idhub-address` param relating to the unique Litentry/IDHub address
- The extrinsic should then look-up the `ruleset-id` param and run the associated  functionality which should validate the following statements are true:
  - The `idhub-address` has both linked and verified at least one Web2.0 account
  - The `idhub-address` has **NOT** linked at least one Web3 account

**Comment by StamfordDigital** [comment]
@BillyWooo has confirmed this ticket has been completed.
